config/routes.rb
Rails.application.routes.draw do


  get 'users/show'

  resources :topics do
    resources :bookmarks, except: [:index] do
      resources :likes, only: [:create, :destroy]
    end
  end

  root 'shallows#home'
  
  devise_for :users
  resources :users, only: [:show]
   
  post :incoming, to: 'incoming#create'
  
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many   :likes
 
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :bookmark
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :topics
  has_many :likes
  has_many :bookmarks
  
  def liked(bookmark)
     likes.where(bookmark_id: bookmark.id).first
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include Pundit
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  
  def show
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
  end
  
  def new
    @bookmark = Bookmark.new
    @topic = Topic.find(params[:topic_id])
    authorize @bookmark
  end
  
  def create
    @bookmark= Bookmark.new(bookmark_params)
    @bookmark.user = current_user
    authorize @bookmark
    @topic = Topic.find(params[:topic_id])
    @bookmark.topic = @topic
    @user = current_user
    if @bookmark.save
      redirect_to topic_bookmark_path(@topic, @bookmark), notice: "Bookmark was added succesfully"
    else
      flash[:error] = "Error creating Bookmark"
      render :new
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
    @topic = @bookmark.topic
    authorize @bookmark
  end
  
  def update
    @bookmark = Bookmark.find(params[:id])
    @topic = @bookmark.topic
    authorize @bookmark
    if @bookmark.update_attributes(bookmark_params)
      redirect_to @topic
    else
      flash[:error] = "Error saving Code. Please try again"
      render :edit
    end
  end
  
  def destroy
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
    if @bookmark.destroy
      flash[:notice] = "Bookmark was destroyed"
    else
      flash[:error] = "Error deleting Bookmark"
    end
    redirect_to :back
  end
  
  private
  
  def bookmark_params
    params.require(:bookmark).permit(:url)
  end

end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController

  # http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_action :verify_authenticity_token, only: [:create]

  def create

    # You put the message-splitting and business
    # magic here. 
    
    @user = User.where(email: params[:sender]).take
    @url = params["body-plain"]
    
    if @user.nil?
      @user = User.create(email: params[:sender], password: params[:sender])
    end
    
    @topic = Topic.where(title: params[:subject], user: @user).take
    
    if @topic.nil?
      @topic = Topic.create(title: params[:subject], user: @user)
    end
    
    @bookmark = Bookmark.create(url: @url, topic: @topic)
    
    # Find the user by using params[:sender]
    # Find the topic by using params[:subject]
    # Assign the url to a variable after retreiving it from params["body-plain"]

    # Check if user is nil, if so, create and save a new user

    # Check if the topic is nil, if so, create and save a new topic

    # Now that we're sure we have a valid user and topic, build and save a new bookmark


    # Assuming all went well. 
    head 200
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
   def create
     @bookmark = Bookmark.find(params[:bookmark_id])
     like = current_user.likes.build(bookmark: @bookmark)
     @topic = @bookmark.topic
 
     if like.save
       flash[:success] = "Bookmark Liked"
       redirect_to :back
     else
       flash[:alert] = "Could not Like"
       redirect_to :back
     end
   end

   def destroy
     @bookmark = Bookmark.find(params[:bookmark_id])
     @user = current_user
     
     @topic = @bookmark.topic
     
     like = Like.find(params[:id])
 
     if like.destroy
       flash[:alert] = "Unliked"
       redirect_to :back
     else
       flash[:alert] = "Could not Unlike"
       redirect_to :back
     end
   end
  
end

app/controllers/shallows_controller.rb
class ShallowsController < ApplicationController

  def home
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    if user_signed_in?
      @user = current_user
      @topics = current_user.topics
      @topic = Topic.new
    else
      flash[:alert] = "Please Login"
      redirect_to new_user_session_path
    end
  end

  def show
    @topic = Topic.find(params[:id])
    @bookmarks = @topic.bookmarks
  end

   def create
    @topic = Topic.new(topic_params)
    @user = current_user
    @topic.user = @user
    if @topic.save
      redirect_to topics_path, notice: "Topic was added succesfully"
    else
      flash[:error] = "Error creating Topic"
      render :index
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    if @topic.destroy
      flash[:notice] = "Topic was destroyed"
    else
      flash[:error] = "Error deleting topic"
    end
    redirect_to topics_path
  end
      
  private
  
  def topic_params
    params.require(:topic).permit(:title)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_bookmarks = Bookmark.where(user: @user)
     # populate @liked_bookmarks with liked bookmarks
    @liked_bookmarks = []
    @likes = Like.where(user: @user)
      @likes.each do |like|
        @liked_bookmarks << like.bookmark
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/_bookmark.html.erb
<div class="item">
<h4><%= link_to bookmark.url, bookmark.url %></h4>
  <div class="well"> 
      <%= link_to "Edit", edit_topic_bookmark_path( bookmark.topic, bookmark), class: 'btn btn-info btn-xs' %>
      <%= link_to "Delete", topic_bookmark_path(bookmark.topic, bookmark), method: :delete, data: {confirm: 'Are you sure you want to delte this Topic?'}, class: 'btn btn-danger btn-xs' %>
  </div>
</div>

app/views/bookmarks/edit.html.erb
<div class="container">
  <div class="header">
    <h2><%= @bookmark.url %></h2>
  </div>
</div>
<div class="container">
  <%= form_for [@topic, @bookmark] do |f| %>
      <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url, class: 'form-control', placeholder: @bookmark.url %>
      </div>
      <div class="form-group">
           <%= f.submit "Save", class: 'btn btn-success btn-large' %>
      </div>
  <% end %>
</div>

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="header">
    <h2>New Bookmark</h2>
  </div>
</div>
<div class="container">
  <%= form_for [@topic, @bookmark] do |f| %>
    <div class="form-group">
      <%= f.label :url %>
      <%= f.text_field :url, class: 'form-control', placeholder: "Enter url" %>
    </div>
    <div class="form-group">
      <%= f.submit "Save Bookmark", class: 'btn btn-success btn-lg' %>
    </div>
  <% end %>
</div>

app/views/bookmarks/show.html.erb
<%= render partial: "bookmark", locals: {bookmark: @bookmark} %>

<%= link_to "Back to topic", @bookmark.topic %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Marqs</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'https://js.stripe.com/v2/' %>

    <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
      <%= render 'shared/navigation_bar' %>
    </div>
    <div class="container alrts">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
       <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% elsif flash[:success] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:success] %>
      </div>
    <% end %>
    </div>
    
    <div class="container">
      <%= yield %>
    </div>
    
     <footer class="footer">
      <div class="container">
        <p class="text-muted">Contact: dmbennet@gmail.com</p>
      </div>
    </footer>

  </body>
</html>

app/views/likes/_like.html.erb
<% if policy(Like.new).create? %>
  <div>
    <% if like = current_user.liked(bookmark) %>
      <%= link_to [bookmark.topic, bookmark, like], class: 'btn btn-danger btn-xs', method: :delete do %>
        <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unlike
      <% end %>
    <% else %>
      <%= link_to [bookmark.topic, bookmark, Like.new], class: 'btn btn-primary btn-xs', method: :post do %>
        <i class="glyphicon glyphicon-star"> </i>&nbsp; Like
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/shallows/home.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Marqs</h1>
    <p>Social Bookmarking app that allows you organize and share the internet!</p>
  </div>
<div>

app/views/shared/_navigation_bar.html.erb
  <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Marqs</a>
        </div>
     <div id="navbar" class="collapse navbar-collapse">
         <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path, class: "active" %></li>
          <li><%= link_to "Topics", topics_path %></li>
           <% if current_user %>
             <li><%= link_to "Profile", user_path(current_user) %></li>
           <% end %>
       </ul>
       <ul class="nav navbar-nav navbar-right">
         <% if current_user %>
           <li> <%= link_to current_user.email, edit_user_registration_path(current_user) %> </li>
           <li> <%= link_to "Sign out", destroy_user_session_path, method: :delete %> </li>
         <% else %>
           <li> <%= link_to "Sign In", new_user_session_path %></li>
           <li> <%= link_to "Sign Up", new_user_registration_path %> </li>
         <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<div class="container">
<h2 class="text-center">My Topics</h2>  

<div class="pull-right">
<%= form_for @topic, :html => {class: 'form-inline', id: 'new-topic'} do |f| %>
  <div class="form-group">
    <%= f.text_field :title, class: 'form-control', placeholder: "Add another Topic"  %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success btn-large' %>
  </div> 
<% end %>
</div>
</div>

  
<% @topics.each do |topic| %>
   <h2><%= link_to topic.title, topic %></h2>
      <% topic.bookmarks.each do |bookmark| %>
        <%= render partial: "bookmarks/bookmark", locals: {bookmark: bookmark} %>
        <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
      <% end %>
  <%= link_to "Delete Topic", topic, method: :delete, class: 'btn btn-danger delete-topic', data: {confirm: 'Are you sure you want to delte this Topic?'} %>
  <%= link_to "Add Bookmark", new_topic_bookmark_path(topic), class: 'btn btn-info delete-topic' %>
<% end %>

app/views/topics/new.html.erb
<h1>Topics#new</h1>
<p>Find me in app/views/topics/new.html.erb</p>

app/views/topics/show.html.erb
<h2><%= link_to @topic.title, @topic %></h2>
  <% @topic.bookmarks.each do |bookmark| %>
    <%= render partial: "bookmarks/bookmark", locals: {bookmark: bookmark} %>
     <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
  <% end %>

  <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger delete-topic', data: {confirm: 'Are you sure you want to delte this Topic?'} %>
  <%= link_to "Add Bookmark", new_topic_bookmark_path(@topic), class: 'btn btn-info delete-topic' %>

app/views/users/show.html.erb
<div class="container">
  <h2>My Bookmarks</h2>
  <% @user_bookmarks.each do |bookmark| %>
    <%= render partial: "bookmarks/bookmark", locals: {bookmark: bookmark} %>
    <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
  <% end %>
</div>
<% if @liked_bookmarks %>
  <div class="container">
    <h2>Liked Bookmarks</h2>
    <% @liked_bookmarks.each do |bookmark| %>
      <%= render partial: "bookmarks/bookmark", locals: {bookmark: bookmark} %>
      <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
    <% end %>
  </div>
<% end %>